<a href="https://colab.research.google.com/github/Madhura1618/CODSOFT-TASK-8/blob/main/creditcard.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
credit_card_data = pd.read_csv('/creditcard.csv')

In [ ]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [ ]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
19893,30631,-0.377215,0.973528,1.647077,0.732439,0.024728,-0.541379,0.828488,-0.060740,-0.725148,...,0.228443,0.685913,-0.107687,0.631740,0.126366,-0.327633,0.056522,0.033139,29.90,0.0
19894,30631,1.209281,0.078793,0.061820,0.593730,-0.235772,-0.448524,-0.141196,0.089236,0.411825,...,-0.302369,-0.984051,0.130401,-0.390756,0.105615,0.152881,-0.025292,0.021130,16.00,0.0
19895,30632,1.286596,-1.450336,0.814530,-1.308949,-2.055209,-0.592064,-1.317286,0.032386,-1.720017,...,0.040743,0.262534,-0.045112,0.515660,0.218606,-0.138794,0.026395,0.030885,92.00,0.0
19896,30633,-0.488090,1.018448,0.670593,-0.245462,0.828347,-0.233102,0.662586,-0.040028,-0.279439,...,-0.344859,-0.902035,-0.050171,-1.060827,0.062221,0.150428,0.130266,0.067290,1.99,0.0
19897,30633,-2.609841,2.479357,0.763844,0.044509,-0.645716,0.762867,-1.626415,-7.617854,1.399746,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19898 entries, 0 to 19897
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    19898 non-null  int64
 1   V1      19898 non-null  float64
 2   V2      19898 non-null  float64
 3   V3      19898 non-null  float64
 4   V4      19898 non-null  float64
 5   V5      19898 non-null  float64
 6   V6      19898 non-null  float64
 7   V7      19898 non-null  float64
 8   V8      19898 non-null  float64
 9   V9      19898 non-null  float64
 10  V10     19898 non-null  float64
 11  V11     19897 non-null  float64
 12  V12     19897 non-null  float64
 13  V13     19897 non-null  float64
 14  V14     19897 non-null  float64
 15  V15     19897 non-null  float64
 16  V16     19897 non-null  float64
 17  V17     19897 non-null  float64
 18  V18     19897 non-null  float64
 19  V19     19897 non-null  float64
 20  V20     19897 non-null  float64
 21  V21     19897 non-null  float64
 22  V22     19897 non-null  float64
 23  V23     19897 non-null  float64
 24  V24     19897 non-null  float64
 25  V25     19897 non-null  float64
 26  V26     19897 non-null  float64
 27  V27     19897 non-null  float64
 28  V28     19897 non-null  float64
 29  Amount  19897 non-null  float64
 30  Class   19897 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 4.7 MB

In [ ]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [ ]:
credit_card_data['Class'].value_counts()

0.0    19812
1.0       85
Name: Class, dtype: int64

The data is highly unbalanced

0->Normal transaction
1->fraudulent transaction

In [ ]:
legic = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [ ]:
print(legic.shape)
print(fraud.shape)

(19812, 31)
(85, 31)

In [ ]:
legic.Amount.describe()

count    19812.000000
mean        70.169855
std        205.091118
min          0.000000
25%          5.900000
50%         16.070000
75%         59.950000
max       7879.420000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count      85.000000
mean       93.869647
std       261.736641
min         0.000000
25%         1.000000
50%         1.000000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [ ]:
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,15483.312841,-0.207233,0.215159,0.803126,0.250998,-0.137392,0.104262,-0.108931,0.003328,0.652123,...,0.036041,-0.050458,-0.145393,-0.036602,0.011905,0.121909,0.032495,0.010624,0.006940,70.169855
1.0,17436.164706,-8.862174,6.570214,-12.622087,6.343007,-6.187820,-2.567646,-8.600077,4.519437,-3.041592,...,0.725080,0.536833,-0.395312,-0.385599,-0.275306,0.359543,0.180456,0.907255,0.093985,93.869647

In [ ]:
legic_sample = legic.sample(n=492)

In [ ]:
new_dataset = pd.concat([legic_sample, fraud], axis=0)

In [ ]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
3969,3621,-1.338671,1.080974,1.291196,0.719258,0.101320,0.053896,0.001297,-0.917575,1.638510,...,0.498030,-0.483932,0.037686,0.053566,-0.560078,0.230423,-0.119911,0.321847,27.43,0.0
14053,25005,-0.499046,1.111834,1.905496,0.250534,-0.050891,-0.700157,0.526398,-0.039254,0.854735,...,-0.315860,-0.571107,0.084075,0.525762,-0.361856,0.029455,0.255681,0.116718,0.89,0.0
14069,25047,0.543748,1.853271,-1.290964,1.551395,1.586324,-1.077731,1.315120,-0.766612,1.376226,...,-0.410702,0.003307,0.033170,-0.172075,-0.566850,-0.518748,-0.033460,-0.546814,2.39,0.0
13197,23223,-0.358111,0.595431,0.338404,0.912810,1.375381,5.333997,-1.588957,-1.311564,2.088013,...,1.605779,-2.187991,-0.183368,0.933278,1.122539,-0.312209,0.326016,0.182812,90.63,0.0
9171,13093,1.208676,0.105042,1.027841,0.226617,-0.747359,-0.655428,-0.416311,-0.118166,1.268490,...,-0.269740,-0.537701,0.169499,0.529794,-0.042269,0.717325,-0.087008,0.002045,4.99,0.0

In [ ]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
17480,28755,-30.552380,16.713389,-31.103685,6.534984,-22.105532,-4.977692,-20.371514,20.007208,-3.565738,...,1.816520,-2.288686,-1.460544,0.183179,2.208209,-0.208824,1.232636,0.356660,99.99,1.0
18466,29526,1.102804,2.829168,-3.932870,4.707691,2.937967,-1.800904,1.672734,-0.300240,-2.783011,...,-0.106994,-0.250050,-0.521627,-0.448950,1.291646,0.516327,0.009146,0.153318,0.68,1.0
18472,29531,-1.060676,2.608579,-2.971679,4.360089,3.738853,-2.728395,1.987616,-0.357345,-2.757535,...,-0.063168,-0.207385,-0.183261,-0.103679,0.896178,0.407387,-0.130918,0.192177,0.68,1.0
18773,29753,0.269614,3.549755,-5.810353,5.809370,1.538808,-2.269219,-0.824203,0.351070,-3.759059,...,0.371121,-0.322290,-0.549856,-0.520629,1.378210,0.564714,0.553255,0.402400,0.68,1.0
18809,29785,0.923764,0.344048,-2.880004,1.721680,-3.019565,-0.639736,-3.801325,1.299096,0.864065,...,0.899931,1.481271,0.725266,0.176960,-1.815638,-0.536517,0.489035,-0.049729,30.30,1.0

In [ ]:
new_dataset['Class'].value_counts()

0.0    492
1.0     85
Name: Class, dtype: int64

In [ ]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,15684.073171,-0.274991,0.254943,0.835490,0.196058,-0.114632,0.067207,-0.115017,-0.199672,0.680302,...,0.042582,0.009242,-0.176204,-0.036819,0.024973,0.111779,0.005481,-0.015669,0.012974,67.457683
1.0,17436.164706,-8.862174,6.570214,-12.622087,6.343007,-6.187820,-2.567646,-8.600077,4.519437,-3.041592,...,0.725080,0.536833,-0.395312,-0.385599,-0.275306,0.359543,0.180456,0.907255,0.093985,93.869647

In [ ]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [ ]:
print(Y)

3969     0.0
14053    0.0
14069    0.0
13197    0.0
9171     0.0
        ...
17480    1.0
18466    1.0
18472    1.0
18773    1.0
18809    1.0
Name: Class, Length: 577, dtype: float64

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [ ]:
print(X.shape, X_train.shape, X_test.shape)

(577, 30) (461, 30) (116, 30)

 LogisticRegression

In [ ]:
mode1 = LogisticRegression()

In [ ]:
mode1.fit(X_train, Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
X_train_prediction = mode1.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [ ]:
print('Accuracy om training data :', training_data_accuracy)

Accuracy om training data : 0.9848156182212582

In [ ]:
X_test_prediction = mode1.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [ ]:
print('Accuracy score on test data :',test_data_accuracy)

Accuracy score on test data : 0.9568965517241379